sudo: required
dist: trusty
language: node_js
node_js:
  - '4.1.2'
os:
- linux
- osx
script:
- echo Building MavensMate-app ...
- ./.travis-build.sh
env:
  global:
    secure: "fQQgdB/MGLRMwZr95KmJNfZsBx5fgoA1gS1DgQCLjWaHzvsLYvPV9RA78kQFn0Q6a4L+tV1VPZErYV4w1UArBPMub8XkG/lmCYCaEwhI1huGDjFCBUxv7jgsMi/XJB7vRtAuNQrzJqQW6/yEyCmB8YlHqEwxTD+34A4Uv85ivdtmxQijR6fQSj+jzZtb13eIPofEcDhfUoTocFy6E9RIZn0SR3J6GdNmhom9+NQlEI/9VcwPW7mw7riR9Ka43UqzdVbNVCQFhwF3rF8PuDIp8B35xTfukHwcLOYXAiu0FFdJjy1ozz8vYbsAHJ0EuM8t0EDu0OrlXqXH9wYKI4u1tcoiQGoblIJNxo0jhLNMs37fRgy2pD1x0Tc3cio4gZHsqEBS/6UxBEtS9hYuIf9KKpGa/ToYoRgNmuJHpbdlAWJb+d8pF+ZAAuuRcB64Ti9agzvXEbNz9fH3q4j01NtYOiT45hSdgSzxRbJ38rsVPvwObjiY24zxSfss+soOqEbqJR0zPT1GIje5MEcFHmXludcSjfPyj0yXEN4MJYMWeV5qNN/32VYIb2rq2aWew7KyIPqf75UFBqwd7g0poG+1S/R1PAT+/7gJvfd5B0etsrj6FaZQPqS37DhBAGCqaZdI6GY43SX5vKbtXx5KindC20qrhX2O8FU4pf2i2AY7A/4="