os: 
  - linux
  - osx
language: node_js
node_js:
  - "0.12"
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8
#       - libgnome-keyring-dev

# script: ./.travis-build.sh
script: 
  - "echo Building mavensmate-app ..."
before_deploy: ./.travis-build.sh
deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: "mavensmate-app-$TRAVIS_TAG-linux-x64.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: "mavensmate-app-$TRAVIS_TAG-osx-x64.zip"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx