language: node_js
node_js:
  - "0.12"
script: 
  - "echo Starting mavensmate-app build script ..."
branches:
  except:
    - dev
before_deploy:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get -qq install g++-4.8
  - g++ -v
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - g++ -v
  - sudo apt-get install libgnome-keyring-dev
  # - sudo apt-get install python-keyring
  # - sudo apt-get install python-gnomekeyring
  - cd ..
  - curl -L "https://github.com/npm/npm/archive/v3.2.0.tar.gz" >> npm3.tar.gz
  - tar -xzvf npm3.tar.gz
  - ls
  - cd mavensmate-app/app
  - node ../../npm-3.2.0/bin/npm-cli.js install
  - ls
  # - ../../npm-3.1.3/bin/npm-cli.js install electron-builder --prefix ../../
  - ../../npm-3.2.0/bin/npm-cli.js install electron-builder -g
  - ../../npm-3.2.0/bin/npm-cli.js install electron-packager -g
  - ./node_modules/.bin/electron-rebuild
  - npm run build:linux
  - cd ../dist/linux
  - ls
  - tar -zcvf mavensmate-app.tar.gz -C dist .
deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: "mavensmate-app.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    # all_branches: true