# Test against this version of Node.js
environment:
  matrix:
  - nodejs_version: "4"

platform:
  - x86

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

skip_tags: true

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git reset --hard HEAD
  - npm install npm -g
  - npm install rimraf -g
  - npm install fs-extra -g
  - npm run stage:win
  - npm install
  - npm run build:win
  - node bin\clean.js

build_script:
  - node --version
  - npm --version
  - npm run dist:win