# Test against this version of Node.js
environment:
  matrix:
  - nodejs_version: "0.12"

platform:
  # - x86
  - x64

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - dir

build: off

before_deploy:
  - python -V
  - ps: Install-Product node $env:nodejs_version
  - ps: $exePath = "$($env:USERPROFILE)\nsis-2.46-setup.exe"
  - ps: (New-Object Net.WebClient).DownloadFile('http://ufpr.dl.sourceforge.net/project/nsis/NSIS%202/2.46/nsis-2.46-setup.exe', $exePath)
  - ps: cmd /c start /wait $exePath /S /D=C:\nsis
  - set PATH=C:\nsis;%PATH%
  - if exist %ProgramFiles%\nodejs\npm del %ProgramFiles%\nodejs\npm
  - if exist %ProgramFiles%\nodejs\npm.cmd del %ProgramFiles%\nodejs\npm.cmd
  - npm -g install npm@3
  - set PATH=%APPDATA%\npm;%PATH%
  - set GYP_MSVS_VERSION=2013
  - npm config set python C:\Python27\python.exe
  - mkdir C:\projects\npm-cache
  - npm config set cache C:\projects\npm-cache --global
  - npm config set cache-lock-retries 1000
  - npm config set cache-lock-wait 100000
  - node --version && npm --version
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - set PATH=C:\Program Files\MSBuild\14.0\Bin;%PATH%
  - cd app
  - npm install
  - if exist C:\projects\mavensmate-app\app\node_modules\npm del C:\projects\mavensmate-app\app\node_modules\npm /F /Q  
  - if exist C:\projects\mavensmate-app\app\node_modules\nslog del C:\projects\mavensmate-app\app\node_modules\nslog /F /Q  
  - .\node_modules\.bin\electron-rebuild
  - npm install electron-builder -g
  - npm install electron-packager -g
  - npm run pack:win
  - dir ..\dist\win
  - dir ..\dist\win\win32
  - dir ..\dist\win\win64
  - cd ..\dist\win\win64
  - 7z a tzip "MavensMate Setup.exe"
  - dir
  - cd ..\dist\win\win32
  - 7z a tzip "MavensMate Setup.exe"
  - dir
  - cd ..\..\..\
  - dir

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - type C:\projects\mavensmate-app\app\node_modules\npm-debug.log

cache:
  - C:\nsis
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> C:\projects\mavensmate-app\app\package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> C:\projects\mavensmate-app\app\package.json         # npm cache
  - C:\projects\npm-cache -> C:\projects\mavensmate-app\app\package.json
  - C:\projects\mavensmate-app\app\node_modules -> C:\projects\mavensmate-app\app\package.json

deploy:
   # Deploy to GitHub Releases
  - provider: GitHub
    artifact: .\dist\win\win64\MavensMate Setup.zip           
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
  - provider: GitHub
    artifact: .\dist\win\win64\MavensMate Setup.exe          
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only