# Test against this version of Node.js
environment:
  matrix:
  - nodejs_version: "0.12"

platform:
  - x86
  - x64

install:
  # - where.exe python
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - set PATH=C:\Program Files\MSBuild\14.0\Bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - mkdir C:\projects\npm-cache
  - mkdir C:\projects\npm3-cache
  - npm config set cache C:\projects\npm-cache --global
  # install modules
  - cd ..
  - ps: Start-FileDownload 'https://github.com/npm/npm/archive/v3.2.0.zip' -FileName 'npm3.zip'
  - 7z x npm3.zip
  - dir
  - cd mavensmate-app\app
  - node ..\..\npm-3.2.0\bin\npm-cli.js config set cache C:\projects\npm3-cache --global
  - node ..\..\npm-3.2.0\bin\npm-cli.js install
  - dir
  - ..\..\npm-3.2.0\bin\npm-cli.js install electron-builder -g
  - ..\..\npm-3.2.0\bin\npm-cli.js install electron-packager -g
  - npm cache clean
  - node ..\..\npm-3.2.0\bin\npm-cli.js cache clean
  # - ..\..\npm-3.2.0\bin\npm-cli.js uninstall nslog
  # - ..\..\npm-3.2.0\bin\npm-cli.js install nslog
  # - cacls C:\projects\mavensmate-app /T /E /C /G Everyone:F
  - .\node_modules\.bin\electron-rebuild
  - node ..\..\npm-3.2.0\bin\npm-cli.js run pack:win
  - dir ..\dist\win
  - dir ..\dist\win\win32
  - dir ..\dist\win\win64
  - cd ..\dist\win\win64
  - 7z a tzip MavensMate Setup.exe
  - dir
  - cd ..\dist\win\win32
  - 7z a tzip MavensMate Setup.exe
  - dir
  - cd ..\..\..\
  - dir

# # Don't actually build.
# build: off

# cache:
#   - example\cache

deploy:
   # Deploy to GitHub Releases
  - provider: GitHub
    artifact: .\dist\win\win64\MavensMate Setup.zip           
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
  - provider: GitHub
    artifact: .\dist\win\win64\MavensMate Setup.exe          
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only