# Test against this version of Node.js
environment:
  matrix:
  - nodejs_version: "0.12"

platform:
  - x86
  - x64

install:
  - dir

before_build:
  - dir

before_deploy:
  - python -V
  - ps: Install-Product node $env:nodejs_version
  - if exist %ProgramFiles%\nodejs\npm del %ProgramFiles%\nodejs\npm
  - if exist %ProgramFiles%\nodejs\npm.cmd del %ProgramFiles%\nodejs\npm.cmd
  - npm -g install npm@3
  - set PATH=%APPDATA%\npm;%PATH%
  - set GYP_MSVS_VERSION=2013
  - npm config set python C:\Python27\python.exe
  - mkdir C:\projects\npm-cache
  - npm config set cache C:\projects\npm-cache --global
  - npm config set cache-lock-retries 1000
  - npm config set cache-lock-wait 100000
  - node --version && npm --version
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - set PATH=C:\Program Files\MSBuild\14.0\Bin;%PATH%
  - cd app
  - npm install
  # - npm install --no-bin-links
  - dir
  - dir node_modules
  - if exist C:\projects\mavensmate-app\app\node_modules\npm del C:\projects\mavensmate-app\app\node_modules\npm /F /Q  
  - npm install --prefix C:\projects\mavensmate-app\app npm@3
  - timeout 5
  - .\node_modules\.bin\electron-rebuild
  # - node C:\projects\mavensmate-app\app\node_modules\electron-rebuild\lib\cli.js
  - npm install electron-builder -g
  - npm install electron-packager -g
  # - npm cache clean
  # - .\node_modules\.bin\electron-rebuild
  - npm run pack:win
  - dir ..\dist\win
  - dir ..\dist\win\win32
  - dir ..\dist\win\win64
  - cd ..\dist\win\win64
  - 7z a tzip MavensMate Setup.exe
  - dir
  - cd ..\dist\win\win32
  - 7z a tzip MavensMate Setup.exe
  - dir
  - cd ..\..\..\
  - dir

# # Don't actually build.
# build: off

# cache:
#   - example\cache

deploy:
   # Deploy to GitHub Releases
  - provider: GitHub
    artifact: .\dist\win\win64\MavensMate Setup.zip           
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
  - provider: GitHub
    artifact: .\dist\win\win64\MavensMate Setup.exe          
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only